export const THEME_TOKEN_KEYS = [
  'fontFamily',
  'fontFamilyBody',
  'colorText',
  'colorPrimary',
  'colorDanger',
  'inputBg',
  'inputTextColor',
  'inputBorder',
  'btnPostBg',
  'btnPostText',
  'inputRadius',
  'widgetRadius',
  'widgetBg',
  'cardRadius',
  'replyRadius',
  'dividerColor',
  'cardBg',
  'cardTextColor',
  'replyBg',
  'replyTextColor',
  'quoteAccent',
  'badgeOwner',
  'badgePinned',
  'toastBg',
  'toastTextColor',
  'toastRadius',
  'widgetPadding',
  'inputAreaPadding',
  'cardPadding',
  'replyPadding',
  'btnPostRadius',
  'badgeTextColor',
] as const

export type ThemeTokenKey = typeof THEME_TOKEN_KEYS[number]