export const THEME_TOKEN_KEYS = [
  'fontFamily',
  'fontFamilyBody',
  'colorText',
  'colorPrimary',
  'colorDanger',
  'inputBg',
  'inputTextColor',
  'inputBorder',
  'btnPostBg',
  'btnPostText',
  'radius',
  'widgetRadius',
  'widgetBg',
  'cardRadius',
  'replyRadius',
  'dividerColor',
  'cardBg',
  'cardTextColor',
  'replyBg',
  'replyTextColor',
  'quoteAccent',
  'badgeOwner',
  'badgePinned',
  'toastBg',
  'toastTextColor',
  'toastRadius',
] as const

export type ThemeTokenKey = typeof THEME_TOKEN_KEYS[number]