FROM node:latest AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG PUBLIC_APP_URL
ARG PUBLIC_DEMO_WIDGET_KEY
ENV PUBLIC_APP_URL=$PUBLIC_APP_URL
ENV PUBLIC_DEMO_WIDGET_KEY=$PUBLIC_DEMO_WIDGET_KEY

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4321